-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bank
(
    bank_id integer NOT NULL,
    nama_bank character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT bank_pkey PRIMARY KEY (bank_id)
);

CREATE TABLE IF NOT EXISTS public.pengguna
(
    user_id integer NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nomor_hp character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone,
    CONSTRAINT pengguna_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.transaksi
(
    transaksi_id integer NOT NULL,
    transfer_id integer NOT NULL,
    user_id integer NOT NULL,
    amount integer NOT NULL,
    status character varying(20) COLLATE pg_catalog."default",
    created_at timestamp without time zone,
    CONSTRAINT transaksi_pkey PRIMARY KEY (transaksi_id)
);

CREATE TABLE IF NOT EXISTS public.transfer
(
    transfer_id integer NOT NULL,
    transfer_penerima_id integer NOT NULL,
    transfer_pengirim_id integer NOT NULL,
    CONSTRAINT transfer_pkey PRIMARY KEY (transfer_id)
);

CREATE TABLE IF NOT EXISTS public.transfer_penerima
(
    transfer_penerima_id integer NOT NULL,
    bank_id integer NOT NULL,
    nama_penerima character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nomor_rekening character varying(20) COLLATE pg_catalog."default" NOT NULL,
    keperluan_transfer character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT transfer_penerima_pkey PRIMARY KEY (transfer_penerima_id)
);

CREATE TABLE IF NOT EXISTS public.transfer_pengirim
(
    transfer_pengirim_id integer NOT NULL,
    metode_transfer character varying(50) COLLATE pg_catalog."default",
    atas_nama character varying(100) COLLATE pg_catalog."default",
    nomor_rekening character varying(20) COLLATE pg_catalog."default" NOT NULL,
    bank_id integer,
    CONSTRAINT transfer_pengirim_pkey PRIMARY KEY (transfer_pengirim_id)
);

ALTER TABLE IF EXISTS public.transaksi
    ADD CONSTRAINT fk_transaksi_pengguna FOREIGN KEY (user_id)
    REFERENCES public.pengguna (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transaksi
    ADD CONSTRAINT fk_transaksi_transfer FOREIGN KEY (transfer_id)
    REFERENCES public.transfer (transfer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transfer
    ADD CONSTRAINT fk_transfer_penerima FOREIGN KEY (transfer_penerima_id)
    REFERENCES public.transfer_penerima (transfer_penerima_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transfer
    ADD CONSTRAINT fk_transfer_pengirim FOREIGN KEY (transfer_pengirim_id)
    REFERENCES public.transfer_pengirim (transfer_pengirim_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transfer_penerima
    ADD CONSTRAINT fk_transfer_penerima_bank FOREIGN KEY (bank_id)
    REFERENCES public.bank (bank_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transfer_pengirim
    ADD CONSTRAINT fk_transfer_pengirim_bank FOREIGN KEY (bank_id)
    REFERENCES public.bank (bank_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;